---
# Main Configuration File of plugin BetterSkulls by HimmelKreis4865

# select a cooldown, the time in seconds you have to wait until you can use /skull again
# 1 day = 24 * 60 * 60 = 86400
# 1 hour = 60 * 60 = 3600
cooldown: 86400

# select the format of the item name
# {player} will be replaced with the skull's owner
format: "§6{player}§7's Skull"

#blacklist [true | false]
useBlacklist: "false"
#here you can set blacklisted players, nobody can get a blacklisted head (this feature don't works if the head is already given)
blacklist: ["Player1", "Player2"]

messages:
  no-permission: "§cYou don't have the permission to execute this command, Sorry!"
  under-cooldown: "§cYou have to wait §e{days} §cDays, §e{hours} §cHours, §e{minutes} §cMinutes, §e{seconds} §cSeconds until you can use this command again!"
  not-found: "§cWe couldn't find a player called §e{name}§c, are you sure this player is online?"
  success: "§aYou successfully got the skull of player §e{name}§a!"
  skull-blocked: "§cThe skull from §e{name} $cis blocked! You can't give you a blocked skull!"
...
